### ISSUE TITLE
Delocalize::LocalizedDateTimeParser#default_parse accepts invalid dates

### ISSUE THREAD

**Issue by kakra** [clemens/delocalize#12] opened 2010-10-26 19:36 UTC
I had a very ugly bug that in my tests my application suddenly started to accept invalid leap-year dates when installing delocalize. I went to delocalize, checked it code, run it's test, added a test: It never accepted invalid dates. But when run from my application (script/console), it suddenly started to parse invalid dates like "29. Februar 2009" which became "1. März 2009" in my tested models.

I tracked this down to be a nasty bug in your tests: Your tests pretend that every user has the [:date,:input,:formats] array set - I didn't. This makes my application (but not your tests) fallback to the "default_parse" method which - due to its implementation using Time.zone.local to convert dates - makes 2009/2/29 a valid date by transforming it to 2010/3/1. :-(

I'm preparing a test in my delocalize fork for you to work with on a fix.

**Comment by clemens** [comment] 2015-11-12 11:33
I'm investigating this again now that 1.0.0 is out. The issue is still there but the surroundings have changed: Previously, it was confusing that a model behaved differently depending on whether or not delocalize was used. Now that delocalize works on the controller level, I'm not so sure how to tackle this.

Rails (4.2.4, ActiveRecord + pg gem) does this:

``` ruby
product = Product.new(released_on: '2009-02-29', available_until: '2011-02-29 12:30:45')
product.released_on # => nil
product.available_until # => Tue, 01 Mar 2011 12:30:45 UTC +00:00
product.available_until = '2011-02-31 12:30:45'
product.available_until # => Thu, 03 Mar 2011 12:30:45 UTC +00:00
product.available_until = '2011-02-32 12:30:45'
product.available_until # => nil
product.available_until = '2011-02-29 24:00:00'
product.available_until # => nil
```

So in other words: Rails always sets invalid dates to `nil` but with datetimes/times it tries to be smart and allows values up to 31 for the day and just shifts it to the next month if the date doesn't exist (e.g. 31st April becomes 1st May). Beyond 31 it falls back to `nil` as well.

Ruby itself raises an `ArgumentError` for all invalid `Date` / `DateTime` objects (29th February in a non-leap year is considered invalid, so is 31st April) and an `ArgumentError` when trying to create a `Time` object with a day beyond 31 (but again shifts 31st April to 1st May etc.).

What behavior would we expect for delocalize? Should it still behave the same way as ActiveRecord (since without delocalize the attributes would just be passed through the controller and end up in the model)? Also, does anyone know how other persistence layers (Mongoid, Sequel etc.) behave when given invalid dates/times?

@sobrinho Since you've helped so much already and seem to be an active user, do you have thoughts on this?

**Comment by sobrinho** [comment] 2015-11-30 22:02
I believe the best way would be to raise an exception when the date or time is invalid.

But the problem is to define what is invalid in fact.

DST for instance have a dead hour which is invalid in real life but ruby treats it as valid and we would have to deal with leap seconds too.

So my recommendation would be to behave just like ruby to avoid unnecessary maintenance from us.

**Comment by clemens** [comment] 2016-07-21 08:43
I finally pushed the fix for that. Does anyone have time to verify that this is correct now?

**Comment by sobrinho** [comment] 2016-08-27 18:13
Seems perfect :shipit:

**Comment by DexterTheDragon** [comment] 2017-03-28 22:55
Is raising an exception desirable? Currently you get different results depending on how invalid the date is.

```
001:0:> Delocalize::Parsers::DateTime.new(Date).parse("asdf")
=> nil
002:0:> Delocalize::Parsers::DateTime.new(Date).parse("02/0/2017")
ArgumentError: invalid date
003:0:> Delocalize::Parsers::DateTime.new(Date).parse("02/123/2017")
ArgumentError: argument out of range
```
Note: The fix mentioned in this issue changes that last one to an "ArgumentError: invalid date".

If an exception is to be raised how do we go about informing the user of their mistake? If the params contain multiple dates how do you show a message saying which one is invalid when all you get is "ArgumentError: invalid date"? Handling an exception in the params method of a controller doesn't seem ideal.

At the very least I think parsing a date like "02/0/2017" should return `nil` like it does when parsing a date like "asdf". Another option might be to have delocalize return the original value if it's unable to parse it. That way values like "02/0/2017" and "asdf" will be passed down to the layer that should be handling validations and then it can return a proper "invalid date" validation error to the client. I don't know how a change like this would effect backwards compatibility with previous versions.

P.S. As an implementation note, it would be nice if `Delocalize::Parsers::DateTime#parse` were to raise "ArgumentError: invalid date" on all invalid dates ("02/0/2017", "asdf") but then have `Delocalize::ParameterDelocalizing#delocalize_parse` handle that error to return either `nil` or the original value to the params hash.

**Comment by fernandoluizao** [comment] 2017-03-29 10:25
I personally I dont like return nil. I think it should behave like Date.parse:

```
Date.parse "asd"
ArgumentError: invalid date
Date.parse "10/0/2017"
ArgumentError: invalid date
```

We will probably need to validate with a regular expression.

**Comment by daniel-rikowski** [comment] 2017-03-29 13:03
> P.S. As an implementation note, it would be nice if Delocalize::Parsers::DateTime#parse were to raise "ArgumentError: invalid date" on all invalid dates ("02/0/2017", "asdf") but then have Delocalize::ParameterDelocalizing#delocalize_parse handle that error to return either nil or the original value to the params hash.

I agree, raising exceptions in params would definitely break existing programs. Passing the original value shouldn't pose much of a problem, since that is what Rails does anyway.

As for the parser raising an exception for the "asdf" case: It can be done from `default_parse` instead of `return if parsed.empty? `: https://github.com/clemens/delocalize/blob/master/lib/delocalize/parsers/date_time.rb#L54

**Comment by DexterTheDragon** [comment] 2017-03-29 14:24
Yep. The more I think about it the more I'm convinced that delocalize should leave the original value in the params hash if it's unable to parse it. The role of delocalize is to parse a set of known input formats into a common format. If delocalize is unable to do that the original value should be passed through to allow the validations to check it and set a proper error message.

**Comment by fernandoluizao** [comment] 2017-04-05 16:35
> that delocalize should leave the original value in the params hash if it's unable to parse it

Makes sense... The pull request looks good too.

**Closed** 2017-04-07 08:31 UTC
